[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "arena"
version = "0.0.1"
description = "A repository for Arena project"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.7"
license = { text = "GNU LGPLv3" }

authors = [
    { name = "Sonia De Santis" },
    { name = "Alejandro Astudillo" }
]

maintainers = [
    { email = "sonia.desantis@kuleuven.be" }
]

keywords = ["corridor", "unicycle"]

dependencies = [
    "numpy>=1.20",
    "scipy>=1.8",
    "matplotlib",
    "PyYAML>=6.0",
]

[project.urls]
Homepage = "https://gitlab.kuleuven.be/u0153320/arena-framework"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["ALL"]